version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: media-video-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: media-video-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend-media-video
    container_name: media-video-backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/media-video-test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UPLOAD_DIR=/app/uploads/videos
      - MAX_VIDEO_SIZE=10737418240
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - video_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend-media-video
    container_name: media-video-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo_data:
  redis_data:
  video_uploads:


