version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: media-video-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend-media-video
    container_name: media-video-backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/media-video
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend-media-video
    container_name: media-video-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo_data:


